aws_region                      = "us-west-2"
emr_name                        = "veda_pforge_emr_test"
repository_name                 = "veda_pforge_emr_serverless"
emr_release_label               = "emr-7.0.0"
execution_role_template         = "./emr/execution_role.json.tpl"
daac_blessed_execution_role_arn = "arn:aws:iam::444055461661:role/veda-data-reader-dev"
bucket_suffix                   = "v4"
